'use client';

import { useState } from 'react';

interface Task {
  title: string;
  description: string;
}

interface ExportOptionsProps {
  goal: string;
  users: string;
  constraints: string;
  risks?: string;
  userStories: Task[];
  engineeringTasks: Task[];
}

export default function ExportOptions({ goal, users, constraints, risks, userStories, engineeringTasks }: ExportOptionsProps) {
  const [showExport, setShowExport] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    let markdown = `# Task Specification\n\n`;
    markdown += `## Project Details\n\n`;
    markdown += `**Goal:** ${goal}\n\n`;
    markdown += `**Target Users:** ${users}\n\n`;
    markdown += `**Constraints:** ${constraints}\n\n`;
    
    if (risks) {
      markdown += `**Risks/Unknowns:** ${risks}\n\n`;
    }

    markdown += `---\n\n`;
    markdown += `## User Stories (${userStories.length})\n\n`;
    userStories.forEach((story, index) => {
      markdown += `### ${index + 1}. ${story.title}\n\n`;
      markdown += `${story.description}\n\n`;
    });

    markdown += `---\n\n`;
    markdown += `## Engineering Tasks (${engineeringTasks.length})\n\n`;
    engineeringTasks.forEach((task, index) => {
      markdown += `### ${index + 1}. ${task.title}\n\n`;
      markdown += `${task.description}\n\n`;
    });

    markdown += `---\n\n`;
    markdown += `*Generated by Tasks Generator*\n`;
    
    return markdown;
  };

  const generatePlainText = () => {
    let text = `TASK SPECIFICATION\n`;
    text += `${'='.repeat(50)}\n\n`;
    text += `PROJECT DETAILS\n`;
    text += `-`.repeat(50) + `\n`;
    text += `Goal: ${goal}\n`;
    text += `Target Users: ${users}\n`;
    text += `Constraints: ${constraints}\n`;
    
    if (risks) {
      text += `Risks/Unknowns: ${risks}\n`;
    }

    text += `\n` + `=`.repeat(50) + `\n\n`;
    text += `USER STORIES (${userStories.length})\n`;
    text += `-`.repeat(50) + `\n\n`;
    userStories.forEach((story, index) => {
      text += `${index + 1}. ${story.title}\n`;
      text += `   ${story.description}\n\n`;
    });

    text += `=`.repeat(50) + `\n\n`;
    text += `ENGINEERING TASKS (${engineeringTasks.length})\n`;
    text += `-`.repeat(50) + `\n\n`;
    engineeringTasks.forEach((task, index) => {
      text += `${index + 1}. ${task.title}\n`;
      text += `   ${task.description}\n\n`;
    });

    text += `=`.repeat(50) + `\n`;
    text += `Generated by Tasks Generator\n`;
    
    return text;
  };

  const handleCopy = (format: 'markdown' | 'text') => {
    const content = format === 'markdown' ? generateMarkdown() : generatePlainText();
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (format: 'markdown' | 'text') => {
    const content = format === 'markdown' ? generateMarkdown() : generatePlainText();
    const filename = `task-spec-${Date.now()}.${format === 'markdown' ? 'md' : 'txt'}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (userStories.length === 0 && engineeringTasks.length === 0) {
    return null;
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
      <button
        onClick={() => setShowExport(!showExport)}
        className="w-full flex items-center justify-between px-6 py-4 bg-gradient-to-r from-green-500 to-teal-600 text-white font-semibold rounded-lg hover:from-green-600 hover:to-teal-700 transition shadow-lg"
      >
        <span className="flex items-center gap-2">
          📥 Export Results
        </span>
        <span className="text-2xl">{showExport ? '▼' : '▶'}</span>
      </button>

      {showExport && (
        <div className="mt-6 space-y-4">
          {/* Markdown Export */}
          <div className="p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
            <div className="flex items-center justify-between mb-3">
              <h4 className="font-semibold text-gray-900 dark:text-white">
                📝 Markdown Format
              </h4>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => handleCopy('markdown')}
                className="flex-1 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
              >
                {copied ? '✓ Copied!' : '📋 Copy'}
              </button>
              <button
                onClick={() => handleDownload('markdown')}
                className="flex-1 px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition"
              >
                ⬇️ Download .md
              </button>
            </div>
          </div>

          {/* Plain Text Export */}
          <div className="p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
            <div className="flex items-center justify-between mb-3">
              <h4 className="font-semibold text-gray-900 dark:text-white">
                📄 Plain Text Format
              </h4>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => handleCopy('text')}
                className="flex-1 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
              >
                {copied ? '✓ Copied!' : '📋 Copy'}
              </button>
              <button
                onClick={() => handleDownload('text')}
                className="flex-1 px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600 transition"
              >
                ⬇️ Download .txt
              </button>
            </div>
          </div>

          {/* Preview */}
          <details className="p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
            <summary className="cursor-pointer font-semibold text-gray-900 dark:text-white mb-2">
              👁️ Preview Markdown
            </summary>
            <pre className="text-xs overflow-x-auto bg-white dark:bg-gray-800 p-4 rounded border border-gray-300 dark:border-gray-600 max-h-64">
              {generateMarkdown()}
            </pre>
          </details>
        </div>
      )}
    </div>
  );
}
